services:
  iacs-viewer:
    container_name: iacs_viewer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./data:/app/data
