[project]
name = "iacs-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.1",
    "geopandas>=1.1.1",
    "polars>=1.31.0",
    "waitress>=3.0.2",
]
