[project]
name = "iacs-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.1",
    "flask-migrate>=4.1.0",
    "flask-sqlalchemy>=3.1.1",
    "geoalchemy2>=0.17.1",
    "geopandas>=1.1.1",
    "pip>=25.1.1",
    "polars>=1.31.0",
    "psycopg2-binary>=2.9.10",
    "waitress>=3.0.2",
]
